### Run the parent file first to generate variables: DataPrep.R
### This will use the total rarefied (or better) data and calculate
### Shannon and AnoSim Diversity

library(MASS)
library(vegan)

### Data Manipulation, need to build complete tables consisting of everything to the lowest level possible
dada2.old.bac.all.tiss = merge_samples(dada2.old.bac.rare, "Tissue", fun = "sum")
dada2.old.fun.all.tiss = merge_samples(dada2.old.fun.rare, "Tissue", fun = "sum")
dada2.old.bac.all.year = merge_samples(dada2.old.bac.rare, "Year", fun = "sum")
dada2.old.fun.all.year = merge_samples(dada2.old.fun.rare, "Year", fun = "sum")
dada2.old.bac.all.loc = merge_samples(dada2.old.bac.rare, "Location", fun = "sum")
dada2.old.fun.all.loc = merge_samples(dada2.old.fun.rare, "Location", fun = "sum")
dada2.old.bac.all.geno = merge_samples(dada2.old.bac.rare, "Genotype", fun = "sum")
dada2.old.fun.all.geno = merge_samples(dada2.old.fun.rare, "Genotype", fun = "sum")
dada2.new.bac.all.tiss = merge_samples(dada2.new.bac.rare, "Tissue", fun = "sum")
dada2.new.fun.all.tiss = merge_samples(dada2.new.fun.rare, "Tissue", fun = "sum")
dada2.new.bac.all.year = merge_samples(dada2.new.bac.rare, "Year", fun = "sum")
dada2.new.fun.all.year = merge_samples(dada2.new.fun.rare, "Year", fun = "sum")
dada2.new.bac.all.loc = merge_samples(dada2.new.bac.rare, "Location", fun = "sum")
dada2.new.fun.all.loc = merge_samples(dada2.new.fun.rare, "Location", fun = "sum")
dada2.new.bac.all.geno = merge_samples(dada2.new.bac.rare, "Genotype", fun = "sum")
dada2.new.fun.all.geno = merge_samples(dada2.new.fun.rare, "Genotype", fun = "sum")

### Shannon Diversity
dada2.old.bac.div.OH = diversity(abundances(dada2.old.bac.all.tiss)[,"Outer Husk"], index = "shannon")
dada2.old.bac.div.H = diversity(abundances(dada2.old.bac.all.tiss)[,"Husk"], index = "shannon")
dada2.old.bac.div.OG = diversity(abundances(dada2.old.bac.all.tiss)[,"Outer Grain"], index = "shannon")
dada2.old.bac.div.G = diversity(abundances(dada2.old.bac.all.tiss)[,"Grain"], index = "shannon")
dada2.old.bac.div.2013 = diversity(abundances(dada2.old.bac.all.year)[,"2013"], index = "shannon")
dada2.old.bac.div.2014 = diversity(abundances(dada2.old.bac.all.year)[,"2014"], index = "shannon")
dada2.old.bac.div.UA = diversity(abundances(dada2.old.bac.all.loc)[,"UA"], index = "shannon")
dada2.old.bac.div.DB = diversity(abundances(dada2.old.bac.all.loc)[,"DB"], index = "shannon")
dada2.old.bac.div.Katy = diversity(abundances(dada2.old.bac.all.geno)[,"Katy"], index = "shannon")
dada2.old.bac.div.M202 = diversity(abundances(dada2.old.bac.all.geno)[,"M202"], index = "shannon")
dada2.old.fun.div.OH = diversity(abundances(dada2.old.fun.all.tiss)[,"Outer Husk"], index = "shannon")
dada2.old.fun.div.H = diversity(abundances(dada2.old.fun.all.tiss)[,"Husk"], index = "shannon")
dada2.old.fun.div.OG = diversity(abundances(dada2.old.fun.all.tiss)[,"Outer Grain"], index = "shannon")
dada2.old.fun.div.G = diversity(abundances(dada2.old.fun.all.tiss)[,"Grain"], index = "shannon")
dada2.old.fun.div.2013 = diversity(abundances(dada2.old.fun.all.year)[,"2013"], index = "shannon")
dada2.old.fun.div.2014 = diversity(abundances(dada2.old.fun.all.year)[,"2014"], index = "shannon")
dada2.old.fun.div.UA = diversity(abundances(dada2.old.fun.all.loc)[,"UA"], index = "shannon")
dada2.old.fun.div.DB = diversity(abundances(dada2.old.fun.all.loc)[,"DB"], index = "shannon")
dada2.old.fun.div.Katy = diversity(abundances(dada2.old.fun.all.geno)[,"Katy"], index = "shannon")
dada2.old.fun.div.M202 = diversity(abundances(dada2.old.fun.all.geno)[,"M202"], index = "shannon")
dada2.new.bac.div.OH = diversity(abundances(dada2.new.bac.all.tiss)[,"Outer Husk"], index = "shannon")
dada2.new.bac.div.H = diversity(abundances(dada2.new.bac.all.tiss)[,"Husk"], index = "shannon")
dada2.new.bac.div.OG = diversity(abundances(dada2.new.bac.all.tiss)[,"Outer Grain"], index = "shannon")
dada2.new.bac.div.G = diversity(abundances(dada2.new.bac.all.tiss)[,"Grain"], index = "shannon")
dada2.new.bac.div.2013 = diversity(abundances(dada2.new.bac.all.year)[,"2013"], index = "shannon")
dada2.new.bac.div.2014 = diversity(abundances(dada2.new.bac.all.year)[,"2014"], index = "shannon")
dada2.new.bac.div.UA = diversity(abundances(dada2.new.bac.all.loc)[,"UA"], index = "shannon")
dada2.new.bac.div.DB = diversity(abundances(dada2.new.bac.all.loc)[,"DB"], index = "shannon")
dada2.new.bac.div.Katy = diversity(abundances(dada2.new.bac.all.geno)[,"Katy"], index = "shannon")
dada2.new.bac.div.M202 = diversity(abundances(dada2.new.bac.all.geno)[,"M202"], index = "shannon")
dada2.new.fun.div.OH = diversity(abundances(dada2.new.fun.all.tiss)[,"Outer Husk"], index = "shannon")
dada2.new.fun.div.H = diversity(abundances(dada2.new.fun.all.tiss)[,"Husk"], index = "shannon")
dada2.new.fun.div.OG = diversity(abundances(dada2.new.fun.all.tiss)[,"Outer Grain"], index = "shannon")
dada2.new.fun.div.G = diversity(abundances(dada2.new.fun.all.tiss)[,"Grain"], index = "shannon")
dada2.new.fun.div.2013 = diversity(abundances(dada2.new.fun.all.year)[,"2013"], index = "shannon")
dada2.new.fun.div.2014 = diversity(abundances(dada2.new.fun.all.year)[,"2014"], index = "shannon")
dada2.new.fun.div.UA = diversity(abundances(dada2.new.fun.all.loc)[,"UA"], index = "shannon")
dada2.new.fun.div.DB = diversity(abundances(dada2.new.fun.all.loc)[,"DB"], index = "shannon")
dada2.new.fun.div.Katy = diversity(abundances(dada2.new.fun.all.geno)[,"Katy"], index = "shannon")
dada2.new.fun.div.M202 = diversity(abundances(dada2.new.fun.all.geno)[,"M202"], index = "shannon")
