### Run the parent file first to generate variables: DataPrep.R
### This will take the count data, normalize all counts to one,
### Combine the OTUs into respective categories, then generate a Venn 
### Diagram 

library(VennDiagram)

### Data Manipulation, need to build complete tables consisting of everything to the lowest level possible
dada2.old.bac.all.tiss = otu_table(merge_samples(dada2.old.bac.pseq, "Tissue", fun = "sum"))[c("Grain", "Outer Grain", "Husk", "Outer Husk")]
dada2.old.bac.all.tiss[dada2.old.bac.all.tiss >= 1] = 1
dada2.old.fun.all.tiss = otu_table(merge_samples(dada2.old.fun.pseq, "Tissue", fun = "sum"))[c("Grain", "Outer Grain", "Husk", "Outer Husk")]
dada2.old.fun.all.tiss[dada2.old.fun.all.tiss >= 1] = 1
dada2.new.bac.all.tiss = otu_table(merge_samples(dada2.new.bac.pseq, "Tissue", fun = "sum"))[c("Grain", "Outer Grain", "Husk", "Outer Husk")]
dada2.new.bac.all.tiss[dada2.new.bac.all.tiss >= 1] = 1
dada2.new.fun.all.tiss = otu_table(merge_samples(dada2.new.fun.pseq, "Tissue", fun = "sum"))[c("Grain", "Outer Grain", "Husk", "Outer Husk")]
dada2.new.fun.all.tiss[dada2.new.fun.all.tiss >= 1] = 1

### Venn Diagram Builder
dada2.old.bac.venn = draw.quad.venn(area1 = sum(dada2.old.bac.all.tiss[1]), area2 = sum(dada2.old.bac.all.tiss[2]), area3 = sum(dada2.old.bac.all.tiss[3]), area4 = sum(dada2.old.bac.all.tiss[4]), n12 = sum(apply(dada2.old.bac.all.tiss[c(1,2)] == c(1,1), 2, prod)), n13 = sum(apply(dada2.old.bac.all.tiss[c(1,3)] == c(1,1), 2, prod)), n14 = sum(apply(dada2.old.bac.all.tiss[c(1,4)] == c(1,1), 2, prod)), n23 = sum(apply(dada2.old.bac.all.tiss[c(2,3)] == c(1,1), 2, prod)), n24 = sum(apply(dada2.old.bac.all.tiss[c(2,4)] == c(1,1), 2, prod)), n34 = sum(apply(dada2.old.bac.all.tiss[c(3,4)] == c(1,1), 2, prod)), n123 = sum(apply(dada2.old.bac.all.tiss[c(1,2,3)] == c(1,1,1), 2, prod)), n124 = sum(apply(dada2.old.bac.all.tiss[c(1,2,4)] == c(1,1,1), 2, prod)), n134 = sum(apply(dada2.old.bac.all.tiss[c(1,3,4)] == c(1,1,1), 2, prod)), n234 = sum(apply(dada2.old.bac.all.tiss[c(2,3,4)] == c(1,1,1), 2, prod)), n1234 = sum(apply(dada2.old.bac.all.tiss == c(1,1,1,1), 2, prod)), category = c("Grain", "Outer Grain", "Husk", "Outer Husk"), fill = c("red", "orange", "blue", "green"), fontface = rep("plain", 15), fontfamily = rep("sans", 15), cex = rep(1, 15), cat.fontface = rep("plain", 4), cat.fontfamily = rep("sans", 4), cat.cex = rep(1, 4), lwd = rep(0.5, 4))
dada2.old.fun.venn = draw.quad.venn(area1 = sum(dada2.old.fun.all.tiss[1]), area2 = sum(dada2.old.fun.all.tiss[2]), area3 = sum(dada2.old.fun.all.tiss[3]), area4 = sum(dada2.old.fun.all.tiss[4]), n12 = sum(apply(dada2.old.fun.all.tiss[c(1,2)] == c(1,1), 2, prod)), n13 = sum(apply(dada2.old.fun.all.tiss[c(1,3)] == c(1,1), 2, prod)), n14 = sum(apply(dada2.old.fun.all.tiss[c(1,4)] == c(1,1), 2, prod)), n23 = sum(apply(dada2.old.fun.all.tiss[c(2,3)] == c(1,1), 2, prod)), n24 = sum(apply(dada2.old.fun.all.tiss[c(2,4)] == c(1,1), 2, prod)), n34 = sum(apply(dada2.old.fun.all.tiss[c(3,4)] == c(1,1), 2, prod)), n123 = sum(apply(dada2.old.fun.all.tiss[c(1,2,3)] == c(1,1,1), 2, prod)), n124 = sum(apply(dada2.old.fun.all.tiss[c(1,2,4)] == c(1,1,1), 2, prod)), n134 = sum(apply(dada2.old.fun.all.tiss[c(1,3,4)] == c(1,1,1), 2, prod)), n234 = sum(apply(dada2.old.fun.all.tiss[c(2,3,4)] == c(1,1,1), 2, prod)), n1234 = sum(apply(dada2.old.fun.all.tiss == c(1,1,1,1), 2, prod)), category = c("Grain", "Outer Grain", "Husk", "Outer Husk"), fill = c("red", "orange", "blue", "green"), fontface = rep("plain", 15), fontfamily = rep("sans", 15), cex = rep(1, 15), cat.fontface = rep("plain", 4), cat.fontfamily = rep("sans", 4), cat.cex = rep(1, 4), lwd = rep(0.5, 4))

tiff(filename = "BacVenn.tif", units = "px", width = 2000, height = 1188, res = 360)

dada2.new.bac.venn = draw.quad.venn(area1 = sum(dada2.new.bac.all.tiss[1]), area2 = sum(dada2.new.bac.all.tiss[2]), area3 = sum(dada2.new.bac.all.tiss[3]), area4 = sum(dada2.new.bac.all.tiss[4]), n12 = sum(apply(dada2.new.bac.all.tiss[c(1,2)] == c(1,1), 2, prod)), n13 = sum(apply(dada2.new.bac.all.tiss[c(1,3)] == c(1,1), 2, prod)), n14 = sum(apply(dada2.new.bac.all.tiss[c(1,4)] == c(1,1), 2, prod)), n23 = sum(apply(dada2.new.bac.all.tiss[c(2,3)] == c(1,1), 2, prod)), n24 = sum(apply(dada2.new.bac.all.tiss[c(2,4)] == c(1,1), 2, prod)), n34 = sum(apply(dada2.new.bac.all.tiss[c(3,4)] == c(1,1), 2, prod)), n123 = sum(apply(dada2.new.bac.all.tiss[c(1,2,3)] == c(1,1,1), 2, prod)), n124 = sum(apply(dada2.new.bac.all.tiss[c(1,2,4)] == c(1,1,1), 2, prod)), n134 = sum(apply(dada2.new.bac.all.tiss[c(1,3,4)] == c(1,1,1), 2, prod)), n234 = sum(apply(dada2.new.bac.all.tiss[c(2,3,4)] == c(1,1,1), 2, prod)), n1234 = sum(apply(dada2.new.bac.all.tiss == c(1,1,1,1), 2, prod)), category = c("Grain", "Outer Grain", "Husk", "Outer Husk"), fill = c("red", "orange", "blue", "green"), fontface = rep("plain", 15), fontfamily = rep("sans", 15), cex = rep(1, 15), cat.fontface = rep("plain", 4), cat.fontfamily = rep("sans", 4), cat.cex = rep(1, 4), lwd = rep(0.5, 4))

dev.off()

dada2.new.fun.venn = draw.quad.venn(area1 = sum(dada2.new.fun.all.tiss[1]), area2 = sum(dada2.new.fun.all.tiss[2]), area3 = sum(dada2.new.fun.all.tiss[3]), area4 = sum(dada2.new.fun.all.tiss[4]), n12 = sum(apply(dada2.new.fun.all.tiss[c(1,2)] == c(1,1), 2, prod)), n13 = sum(apply(dada2.new.fun.all.tiss[c(1,3)] == c(1,1), 2, prod)), n14 = sum(apply(dada2.new.fun.all.tiss[c(1,4)] == c(1,1), 2, prod)), n23 = sum(apply(dada2.new.fun.all.tiss[c(2,3)] == c(1,1), 2, prod)), n24 = sum(apply(dada2.new.fun.all.tiss[c(2,4)] == c(1,1), 2, prod)), n34 = sum(apply(dada2.new.fun.all.tiss[c(3,4)] == c(1,1), 2, prod)), n123 = sum(apply(dada2.new.fun.all.tiss[c(1,2,3)] == c(1,1,1), 2, prod)), n124 = sum(apply(dada2.new.fun.all.tiss[c(1,2,4)] == c(1,1,1), 2, prod)), n134 = sum(apply(dada2.new.fun.all.tiss[c(1,3,4)] == c(1,1,1), 2, prod)), n234 = sum(apply(dada2.new.fun.all.tiss[c(2,3,4)] == c(1,1,1), 2, prod)), n1234 = sum(apply(dada2.new.fun.all.tiss == c(1,1,1,1), 2, prod)), category = c("Grain", "Outer Grain", "Husk", "Outer Husk"), fill = c("red", "orange", "blue", "green"), fontface = rep("plain", 15), fontfamily = rep("sans", 15), cex = rep(1, 15), cat.fontface = rep("plain", 4), cat.fontfamily = rep("sans", 4), cat.cex = rep(1, 4), lwd = rep(0.5, 4))

